<h1>About</h1>
<div class="row">
    <div class="col-md-12">
        <p>
            The award-winning MK Data Hub is a data infrastructure that supports the acquisition and management of both
            static and dynamic data from a variety of sources. The MK Data Hub was initially developed within the MK:Smart
            project, a flagship £17.2M UK initiative, which focused on progressing the smart city agenda in Milton Keynes.
            More recently it has been used to support the CityLABS innovation programme and the 1st International
            Competition on Robots in Smart Cities and it will also provide a key infrastructure component to the
            state-of-art 5G network that will be deployed in Milton Keynes in 2020 as part of the current
            <a href="http://kmi.open.ac.uk/projects/name/mk:5g" target="_blank">MK:5G project</a>.
        </p>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <h2>The team</h2>
    </div>
    <div class="col-md-6 text-center">
        <a href="http://kmi.open.ac.uk/people/member/enrico-daga" target="_blank">
            <img src="/img/team/enrico-daga.png"><br />
            <strong>Dr Enrico Daga</strong></a><br />
        Research Fellow
    </div>
    <div class="col-md-6 text-center">
        <a href="http://kmi.open.ac.uk/people/member/jason-carvalho" target="_blank">
            <img src="/img/team/jason-carvalho.png"><br />
            <strong>Jason Carvalho</strong></a><br />
        Project Officer
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <h2>Related projects</h2>
    </div>
    <div class="col-md-4 text-left p-3">
        <h4><a href="https://mkdf.github.io/" target="_blank">MK Data Factory</a></h4>
        <a href="https://mkdf.github.io/" target="_blank"><img src="/img/mkdf-logo.png" alt="MK Data Factory" class="img-fluid p-3"></a>
        <p class="text-left">MK Data Hub is built on the <em>MK Data Factory</em> framework.</p>
    </div>
    <div class="col-md-8 text-left p-3">
        <h4><a href="https://github.com/mkdf/api-factory/blob/master/README.md" target="_blank">API Factory</a></h4>
        <p>The <a href="https://github.com/mkdf/api-factory/blob/master/README.md" target="_blank">API Factory</a> is a
            WebAPI for managing and sharing streaming data with the support of open
            schema specifications. Its main goal is to make it easier to set up APIs on-demand, based
            on specifications such as JSON schemas. MK Data Hub makes use of the API Factory for reading
            and writing to Stream API datasets.</p>
    </div>

</div>
