<h1>Terms and Conditions for Data Providers</h1>
<p>The MK Data Hub portal is provided by The Open University. It was part of the MK:Smart project, which was funded by
    HEFCE. In these Terms and Conditions, when it says 'we' or 'us', it means The Open University, which is incorporated
    by Royal Charter (RC 000391), an exempt charity in England and Wales and a charity registered in Scotland (SC
    038302). By using the MK Data Hub portal you agree to be bound by these Terms and Conditions, which shall take
    effect immediately on your first use of the MK Data Hub portal. If you do not agree to be bound by all of the
    following Terms and Conditions please do not complete your registration.</p>
<p>You must be over the age of 16 to register for an account on the MK Data Hub portal. You will need to provide us with
    some personal details about yourself. We will protect your personal data in accordance with the UK Data Protection
    Act (see our Privacy Policy for more details). If you disable your account we will not automatically delete content
    that you have submitted to the MK Datahub<span style="line-height: 1.5;">. </span></p>
<p>The Open University may change these Terms and Conditions from time to time and so you should check these terms
    regularly. Your continued use of the MK Data Hub will be deemed acceptance of the updated or amended Terms and
    Conditions. If you do not<br/>agree to the changes, you should cease using this website.</p>
<p>The Open University may bring any rights granted to you to an end at any time without <span
        style="line-height: 1.5;">necessarily providing any notice to you.</span></p>
<h3>Conditions of Use</h3>
<p>You agree to use the MK Data Hub portal only for lawful purposes, and in a way that does not infringe the
    rights <span style="line-height: 1.5;">of, restrict or inhibit anyone else’s use and enjoyment of this Site. Prohibited behaviour </span><span
        style="line-height: 1.5;">includes harassing or causing distress or inconvenience to any person, transmitting obscene or </span><span
        style="line-height: 1.5;">offensive content or disrupting the normal flow of dialogue. You may not impersonate another </span><span
        style="line-height: 1.5;">person.</span></p>
<h3>Intellectual Property</h3>
<p>All copyright, trade marks, design rights, patents and other intellectual property rights (registered and
    unregistered) and all content located on the MK Data Hub portal other them user-provided content shall remain vested
    in The Open University or the corresponding member of the MK:Smart project.</p>
<h3>Contributions to the Open University</h3>
<p>By sharing data through the MK Data Hub, you agree to the Terms and Conditions for Data Providers, which states that
    your remain the owner, rights holder and responsible for the data shared.</p>
<h3>Accuracy of Content and Information</h3>
<p>The Open University is not able to guarantee that information contained on or available via the MK Data Hub
    portal will continue to be accurate. You confirm that you have not relied on any such information and any
    arrangements made between you and any other person, using or named on the MK Data Hub portal is entirely at your
    sole risk and responsibility.<br/>Information contained in or accessible via the MK Data Hub changes on a regular
    basis. We may make improvements or alterations at any time and without notice. If any links to another website
    appear on the MK Data Hub portal, The Open University accepts no responsibility<br/>or liability for the content of
    that website (whether under our control or otherwise). Any link is not intended to be, nor should be construed as,
    an endorsement of any kind by us.</p>
<p>Should we link to other website we will try to make it as clear as possible that you are leaving the MK Data Hub
    portal<span style="line-height: 1.5;">. It is your responsibility to check the terms and conditions and privacy policy on any </span><span
        style="line-height: 1.5;">other website that you visit.</span></p>
<h3>Liability</h3>
<p>We do not guarantee that:</p>
<ol>
    <li>use of the MK Data Hub portal will be compatible with all hardware and software;</li>
    <li>use of the MK Data Hub portal will be uninterrupted or error or virus free;</li>
    <li>use of the MK Data Hub portal will deliver any specific outcome for its users; or that</li>
    <li>defects will be corrected.</li>
</ol>
<p>You must take appropriate steps to ensure that you regularly check for viruses when using the MK Data Hub portal on
    any device.</p>
<p>We make no statement about the suitability of the content, information and services contained on, or accessed via,
    the MK Data Hub portal. All warranties, terms and conditions in this regard, including all warranties, terms and
    conditions implied by statute or otherwise, of satisfactory quality and fitness for purpose are excluded to the
    fullest permitted by law. For the avoidance of doubt this includes materials accessed via links to websites
    (including home pages, web pages or documents they contain) operated by third parties.<br/>We further exclude to the
    fullest extent permissible by law all liability for damages and direct, indirect or consequential loss (all three of
    which terms include pure economic loss, loss of profits, loss of business, business interruption, depletion of
    goodwill and like loss) or otherwise incurred by you or any third party and arising out of or in any way connected
    with the use of the MK Data Hub portal or its content, whether based on contract, tort, strict liability or
    otherwise.<br/>You will defend, indemnify and hold harmless us, our affiliates and our officers,
    directors, employees and agents from and against any and all claims, liabilities, damages, losses or expenses,
    including reasonable legal costs, arising out of or in any way connected with any breach by you of these Terms and
    Conditions.</p>
<h3>Complete Agreement</h3>
<p>These Terms and Conditions (including the privacy statement and the Terms and Conditions for data providers) contain
    all the terms and conditions applicable to your use of the Data Hub portal. Nothing contained on the Data Hub
    portal is intended to be, nor should be construed as an offer by us to enter into, a contractual relationship with
    you or anyone else except on these Terms and Conditions.</p>
<h3>Jurisdiction and acceptance of these Terms and Conditions</h3>
<p>These Terms and Conditions, and any dispute in relation to the materials available from the MK Data Hub portal, are
    governed by English law. The English courts have exclusive jurisdiction to settle any disputes which may arise out
    of or in connection with the Terms and Conditions or use of the MK Data Hub portal.</p>