<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?= $this->headTitle('SPICE Linked Data Hub')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ->appendStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
        ->prependFile($this->basePath('js/jquery-ui.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ?>
<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"/>
    </head>
    <body>
<header>
    <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-spice fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/SPICE-LDH-logo-long.svg') ?>" height="38" alt="SPICE Linked Data Hub"/>&nbsp;
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?= $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(2)
                        ->setMaxDepth(2)
                        ->setPartial('partial/menu')?>
                    <!-- <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                        </li>
                    </ul> -->
                </div>
            </div>
        </nav>
</header>
<!-- Begin page content -->
<main role="main" class="container main-page-container">
    <?= $this->content ?>
</main>
<br clear="all" />
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="text-muted text-left">
<?php /*?>
                    <a href="<?= $this->url('content', ['action' => 'static', 'page' => 'about'])?>">About</a><br />
                    <a href="<?= $this->url('content', ['action' => 'static', 'page' => 'termsconditions'])?>">Terms and Conditions</a><br />
                    <a href="<?= $this->url('content', ['action' => 'static', 'page' => 'contact'])?>">Contact</a><br />
<?php */ ?>         <a href="#">About</a><br />
                    <a href="#">Terms and Conditions</a><br />
                    <a href="#">Contact</a><br />
                </span>
            </div>
            <div class="col-md-4 text-center">
                        <small class="text-muted text-right">
        	&copy; <?= date('Y') ?> <!-- - <?= date('Y') ?> --> by The Open University. All rights reserved. <br/>
*<br/>
            Version <?= \Application\Module::VERSION ?>
                        </small>
            </div>
            <!-- <div class="col-md-3 text-center">
                <span class="text-muted text-center"><a href="http://kmi.open.ac.uk/" target="_blank">
                        <img src="/img/kmi-logo.png" width="100" alt="KMi"></a></span>
            </div>
            <div class="col-md-2 text-center">
                <span class="text-muted text-center"><a href="https://isds.kmi.open.ac.uk/" target="_blank">
                        <img src="/img/isds-logo.png" height="60px" alt="ISDS"></a></span>
            </div> -->
            <div class="col-md-4 text-right">
                <span class="text-muted text-center"><a href="http://www.open.ac.uk/" target="_blank">
                        <img src="/img/ou-logo.png" height="60px" alt="The Open University"></a></span>
            </div>

            <!-- <div class="col-md-2 text-center">
                <span class="text-muted text-center"><a href="http://mkdf.github.io/" target="_blank">
                        <img src="/img/mkdf-logo.png" width="100" alt="MK Data Factory"></a></span>
            </div> -->
        </div>

    </div>
</footer>

        <?= $this->inlineScript() ?>
    </body>
</html>
