<?php if ($this->pageCount): ?>
    <?php
        if (!isset($route)){
            $route = $this->route;
        }
    ?>

<nav>
    <ul class="pagination justify-content-center">

        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li class="page-item">
                <a class="page-link" href="<?= $this->url($route, ['action' => $action], ['query'=>array_merge($url_params,['page'=>$this->previous])]); ?>">
                    &laquo;
                </a>
            </li>
        <?php else: ?>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">
                    &laquo;
                </a>
            </li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($route, ['action' => $action], ['query'=>array_merge($url_params,['page'=>$page])]); ?>"><?= $this->escapeHtml($page); ?></a>
                </li>
            <?php else: ?>
                <li class="page-item active">
                    <span class="page-link"><?= $this->escapeHtml($page); ?></span>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li class="page-item">
                <a class="page-link" href="<?php echo $this->url($route, ['action' => $action], ['query'=>array_merge($url_params,['page'=>$this->next])]); ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        <?php else: ?>
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">
                    &raquo;
                </a>
            </li>
        <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>