<div class="jumbotron">
    <h1>SPICE <span class="spice-green">Linked Data Hub</span></h1>

    <p>
        Welcome content
    </p>

</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Explore</h2>
            </div>
            <div class="card-body">
                <p>
A catalogue of Linked Data resources
				</p>

                <p><a class="btn btn-success pull-right" href="<?= $this->url('dataset') ?>">Browse datasets &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Connect</h2>
            </div>
            <div class="card-body">
                <p>
                    The SPICE community ...
                </p>

                <p><a class="btn btn-success pull-right" href="#" >Link your data &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">How to</h2>
            </div>
            <div class="card-body">
                <p>
                   Documentation
                </p>

                <p><a class="btn btn-success pull-right" href="#" >FAQ &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
