
<!--
<div class="jumbotron">

<img src="../img/SPICE-LDH-logo-long.svg"/>
</div>
-->

<div class="row">
    <div class="col-md-12">
        <hr />
    </div>

    <div class="col-md-7 py-4">
        <h1>SPICE Linked Data Hub</h1>

        <p>The SPICE Linked Data Hub forms part of the Linked Data infrastructure used within the wider <a href="https://spice-h2020.eu/" target="_blank">SPICE project</a>,
            an EU-H2020 funded project
        dedicated to citizen curation and cultural heritage.</p>
        <p>The Linked Data Hub supports the acquisition and management of both static files and dynamic streaming data from a variety of sources.
        </p>
    </div>

    <div class="col-md-1">

    </div>

    <div class="col-md-4 text-center">
        <img src="../img/art-gallery-circle.png" height="300px" class=""/><br/>
        <a href="https://spice-h2020.eu/" target="_blank"><img src="/img/spice-logo.png" class=""></a>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <hr />
    </div>

    <div class="text-center col-md-12">
        <h3>Featured datasets</h3>
    </div>



    <div class="col-md-4 my-3">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a href="https://spice.kmi.open.ac.uk/dataset/details/41">Irish Museum of Modern Art</a></h4>
            </div>
            <div class="card-body">
                <p>
                    Metadata of the Irish Museum of Modern Art collection.
                </p>
                <p class="small"><em>Documents: <?= $spotlight['docCounts']['f9e601f0-06e6-4733-a791-ec42f3aab80e'] ?></em></p>
            </div>
        </div>
    </div>

    <div class="col-md-4 my-3">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a href="https://spice.kmi.open.ac.uk/dataset/details/22">FTM: Palazzo Madama</a></h4>
            </div>
            <div class="card-body">
                <p>
                    Open data from Fondazione Torino Musei: The Palazzo Madama Collection.
                </p>
                <p class="small"><em>Documents: <?= $spotlight['docCounts']['7deccc71-46f5-46d3-9c83-9785aeec4f25'] ?></em></p>
            </div>
        </div>
    </div>

    <div class="col-md-4 my-3">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a href="https://spice.kmi.open.ac.uk/dataset/details/20">FTM: Museo di Arte Orientale</a></h4>
            </div>
            <div class="card-body">
                <p>
                    Open data from Fondazione Torino Musei: The Museo di Arte Orientale Collection.
                </p>
                <p class="small"><em>Documents: <?= $spotlight['docCounts']['e377c7a6-47d5-42b9-8fc4-66d7476e46e5'] ?></em></p>
            </div>
        </div>
    </div>

    <div class="col-md-4 my-3">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a href="https://spice.kmi.open.ac.uk/dataset/details/19">FTM: Galleria di Arete Moderna</a></h4>
            </div>
            <div class="card-body">
                <p>
                    Open data from Fondazione Torino Musei: The Galleria di Arete Moderna Collection.
                </p>
                <p class="small"><em>Documents: <?= $spotlight['docCounts']['d6a1d487-63bb-4eb4-993c-b707248aeca5'] ?></em></p>
            </div>
        </div>
    </div>

    <div class="col-md-4 my-3">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a href="https://spice.kmi.open.ac.uk/dataset/details/24">FTM: Fondo Gabinio</a></h4>
            </div>
            <div class="card-body">
                <p>
                    Open data from Fondazione Torino Musei: The Fondo Gabinio Collection.
                </p>
                <p class="small"><em>Documents: <?= $spotlight['docCounts']['87801597-c115-4493-98b5-2e9a49864a10'] ?></em></p>
            </div>
        </div>
    </div>

    <div class="col-md-4 my-3">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><a href="https://spice.kmi.open.ac.uk/dataset/details/25">The Tate Collection</a></h4>
            </div>
            <div class="card-body">
                <p>
                    2014 snapshot of metadata for around 70,000 artworks that Tate owns or jointly owns with the National Galleries of Scotland.
                    Metadata for around 3,500 associated artists is also included.
                </p>
                <p class="small"><em>Documents: <?= $spotlight['docCounts']['a57c79a6-bed9-42e9-bc5d-c484c337045c'] ?></em></p>
            </div>
        </div>
    </div>

</div>
